name: refresh jsdelivr
run-name: "刷新jsdelivr缓存"
on:
  push:
  workflow_dispatch:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: gacts/purge-jsdelivr-cache@v1.1.0
        with:
          url: |
            https://cdn.jsdelivr.net/gh/bling-yshs/custom-clash-rule@main/proxy.yaml
            https://cdn.jsdelivr.net/gh/bling-yshs/custom-clash-rule@main/direct.yaml
