name: refresh jsdelivr
run-name: 'refresh jsdelivr'
on:
  push:
  workflow_dispatch:

jobs:
  refresh-jsdelivr:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: bling-yshs/purge-jsdelivr-for-directory@v1.0
        with:
          path: ''
          retry: '3'