name: refresh jsdelivr
run-name: "刷新 jsdelivr 缓存"
on:
  push:
  workflow_dispatch:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: bling-yshs/purge-jsdelivr-for-directory@v1.0
        with:
          path: |
            rules