name: upload-to-alist
run-name: 上传到 Alist
on:
  push:
  workflow_dispatch:

jobs:
  refresh-jsdelivr:
    runs-on: ubuntu-22.04
    steps:
      - name: 上传到 Alist
        run: python .github/scripts/up.py admin ${{secrets.ALIST_PASSWORD}} rules /share