name: upload-to-alist
run-name: 上传到 Alist
on:
  push:
  workflow_dispatch:

jobs:
  upload-to-alist:
    runs-on: ubuntu-22.04
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: 上传到 Alist
        uses: bling-yshs/alist-upload@main
        with:
          alist-url: 'https://pan.ystech.top'
          alist-username: 'admin'
          alist-password: ${{secrets.ALIST_PASSWORD}} # <--- 警告：强烈建议使用 Secrets!
          file-path: rules/*.yaml
          remote-dir: share/rules
          overwrite-exist-file: true

