name: upload-to-alist
run-name: 上传到 Alist
on:
  push:
  workflow_dispatch:

jobs:
  upload-to-alist:
    runs-on: ubuntu-22.04
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: 上传到 Alist
        uses: bling-yshs/alist-upload@main
